name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        sdk: [macosx, iphoneos]
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    - name: Build
      run: xcrun -sdk ${{ matrix.sdk }} swift build -v
    - name: Test
      run: xcrun -sdk ${{ matrix.sdk }} swift test -v
