name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        build:
        - platform: macOS
          sdk: macosx
          target: aarch64-apple-macosx15.0
          destination: 'platform=macOS,name=My Mac'
        - platform: iOS
          sdk: iphonesimulator
          target: aarch64-apple-ios18.2-simulator
          destination: 'platform=iOS Simulator,name=iPhone 16'
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    - if: matrix.build.platform != 'macOS'
      name: Download ${{ matrix.build.platform }} Platform
      run: xcodebuild -downloadPlatform ${{ matrix.build.platform }}
    - run: xcodebuild -scheme swift-sfsymbols -showdestinations
    - name: Test
      run: xcodebuild -target ${{ matrix.build.target }} -sdk ${{ matrix.build.sdk }} -scheme swift-sfsymbols -destination '${{ matrix.build.destination }}' test
