name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        build:
        - sdk: macosx
          target: aarch64-apple-macosx15.0
        - sdk: iphoneos
          target: aarch64-apple-ios18.2
        - sdk: iphonesimulator
          target: aarch64-apple-ios18.2-simulator
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4.2.2
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app
    - name: Build
      run: xcrun -sdk ${{ matrix.build.sdk }} swift build -target ${{ matrix.build.target }}
    - name: Test
      run: xcrun -sdk ${{ matrix.build.sdk }} swift test -target ${{ matrix.build.target }}
